### ISSUE TITLE
Vyatka- politics won't change

### ISSUE THREAD

**Issue by pjo71099** [TNODevs/TNO-Bug-Tracker#1444]
### Operating System

windows 10

### HOI4 version

1.12.6.46b6

### TNO version

1.3.0d patch d

### Do you have other mods in use?

None

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB

### Describe the bug

Playing a Vyatka game. Win as Kadets, but politics wont change so locked out of part of focus tree

### Steps to reproduce / Cause of the issue

1. Play Vyatka
2. Win as Kadets

### Expected behaviour

Expected politics to change to liberal democrat to continue with focus tree

### Screenshots

![image](https://user-images.githubusercontent.com/94796453/204097397-914e45e2-8fa5-44f1-a510-99c6d630038e.png)

### Additional information

tried with election during and before intervention in finland

**Comment by Angelblue1852** [comment]
Part of the issue may be due to the elections. When I tried this with similar results, the variables showed that apparently the Liberal Conservatives had won. Not sure if the election results got cleared properly from Komi after the last election or if they got held over from some other nation on mistake.

**Comment by BenZin-BLR** [comment]
Hello. Faced the same problem, tell me, please, is there any solution.
