### ISSUE TITLE
JAP -  Karafuto Oil doesn't generate fuel

### ISSUE THREAD

**Issue by Sainte-Augustine** [TNODevs/TNO-Bug-Tracker#1567]
### Operating System

Windows 11

### HOI4 version

1.12.8

### TNO version

1.4.0

### Do you have other mods in use?

TNO: Allegiances Submod, The  New Order: GDP+Sociatal Development Cheats, The New Order: Cheat Mod++, Toolpakt: Toolpack for TNO

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, MTG, LAR, NSB, BBA

### Describe the bug

After the new update, I discovered while I was training my divisions that the fuel tends to dry up faster than before because Karafuto Oil wasn't generating oil, only leaving the base fuel gain. I tried transferring Karafuto to another country to test if the problem persists and it does.

### Steps to reproduce / Cause of the issue

I guess load a new game of Japan and observe it still has the same issue

### Expected behaviour

Karafuto Oil should be factored into daily fuel gain

### Screenshots

![Screenshot_20230209_022034](https://user-images.githubusercontent.com/124873684/217765942-96c4e255-b9a1-4c6f-b8d3-454e16c42a96.png)

**Comment by Stormeagle449** [comment]
WAD. Japan starts the game with a oil deficit, that's why the oil produced by a single state doesn't factor into the fuel gain.

Also, next time you report a bug please try to play a game without submods/cheats and then report the results. All submods can affect the base game performance in ways we don't know.
