### ISSUE TITLE
Why are there so many focuses that just give Debuffs ? 

### ISSUE THREAD

**Issue by JordenGG** [TNODevs/TNO-Bug-Tracker#1765]
### HOI4 version

1.12.12

### TNO version

Ugly american C 1.4

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Why are there so many focuses that just give Debuffs ? I gotta say, having focuses that give you nothing but debuffs gotta be one of the dumbest desgin choices out there.  All of the debuffs should just be through events or focuses that automatically complete, where at least you wont have to take them yourself.

### Justifications

Its simple Game Desgin that the gameplay should reward the player, especially in these type of games where there is a clear gameplay loop. Having focuses that you are forced to take (and there are even some that you dont need to take) is pretty discouraging. Forcing players to take focuses that do nothing but harm is not fun in any way, you make the player feel like he is destroying his own country, and it makes the player question that it even makes sense, and break their immersion

 

### Screenshots

Best example for bad focuses that are not required is the first Guangdong tree, the  focuses  circiled here just give debuffs, but taking them is entirely optional as the yasunda crisis will happen regardless and you will be better off not taking them

![fffff](https://user-images.githubusercontent.com/84973934/234648019-c63a8648-4de0-46c7-aa37-146493bb9484.png)

And the Whole Nanjing crisis Tree is just terrible, You force players to lose half of their economy in the least fun way by forcing them to click a button and wait for 14 days for the duration of a year, its not fun, and in the end games are supposed to be fun
![24](https://user-images.githubusercontent.com/84973934/234649081-8b276881-4484-4c00-bb05-76ecec58ae2b.png)

### Additional information

Speer's germany's Oil crisis was implemented very well, although it has some focuses that give nothing but negatives, the vast majority of negative stuff came through events that describe thoroughly how everything collapses. If there was instead just a focus that just gave you all these debuffs (or gives events that give these debuffs) many players would quit after the oil crisis because it was just not fun to take focuses that ruin your economy that you built for most of the game.

**Comment by runelead00** [comment]
TNO has to balance gameplay and narrative while designing our focus trees and give them effects that a make sense with actions of each focus.  Sometimes this means focuses will give purely negative effects, like with the Chinese focuses, sometimes it leads to set of trade-offs like the Guangdong focuses (which are not all purely debuffs as has been pointed out elsewhere). While some focuses might be better to auto-complete, one can't account for when players are just going to ignore an option just because they assume it's bad. Most players aren't going to skip those Guangdong focuses, because most players don't see those as negative and if they do, they want to finish the tree more. Same issue with players just not doing Thurmond's tree in the US. Some people want to meta-game to point of just not playing while other will just go with the flow

A focus tree with purely negative or positive effects is just going to become a focus clicker, a mix of effects whether between focuses or within a single focus require the player to do some amount of strategy and leads to more engaging gameplay.
