### ISSUE TITLE
JAP - Faction relations don't change between kaya and ikeda prime ministerships

### ISSUE THREAD

**Issue by Revenindps** [TNODevs/TNO-Bug-Tracker#181]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: TT 1.20
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? None

After getting kaya as the  new PM as japan, your government can collapse leading to the second interregnum. During the event chain influence the next PM, where i got Ikeda. When ikeda was appointed PM, the faction relations in the decision screen didn't change ie. technocrats were still at 90%, conservatives were at around 30%, just like before. Seems to be an issue with the JAP_set_base_faction_approval effect not firing

**Steps to Reproduce/Cause Issue:**

1. Play Japan as usual until the first interregnum.
2. During the interregnum end up with kaya.
3. Go with the middle path like the fool i am, lose all your government stability and most house of peer support.
4. Get your government collapsed.
5. In the second interregnum end up with ikeda.

**Comment by sugjester** [comment]
Instead of making my own post I think I should add to this one:
Faction relations don't change between Takagi and Kaya governments either. 
My relationship with the reformists is excellent and my relationship with the technocrats is terrible, yet I am the technocrats.

Steps to reproduce:
1. get Takagi after 1st interregnum; 
2. don't pay attention to HoP support and fail your government;
3. decide to do a 180° and put the bureaucrats back in charge.

I assume the problem likely exists for other post-second interregnum governments as well.

**Comment by Tarepa** [comment]
fixed
