### ISSUE TITLE
Japan - Bugged Philippines Reconstruction

### ISSUE THREAD

**Issue by MsChoo1** [TNODevs/TNO-Bug-Tracker#2287]
### Operating System

Windows 10

### HOI4 version

1.12.4

### TNO version

1.5.0

### Do you have other mods in use?

Last Waltz: Expanded, Toolpack

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

NSB, BBA

### Describe the bug

Finished Filipino reconstruction with Takagi, event triggered named "Our successor" and had the words "Who to lead after Yulo's assaassination (unecessary loc). Had Quentin Paredes, Claro M. Recto, and Osmena, but the event triggered the Kido faction in Japan to come to power and did not actually have the leader come to power with the KALIBAPI.

### Steps to reproduce / Cause of the issue

Play Japan, install Takagi, win Filipino civil war with the Japanese collaborators, and then finish reconstruction.

### Expected behaviour

When I clicked finish reconstruction, I expected Osema to come to power as Japan deemed him the successor. This did not happen.

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107003909/24302ff0-3758-4305-b938-e73a0912c46f)

**Comment by MsChoo1** [comment]
Adding to this, it also seems to bug party popularity in Japan - gives despotism more party popularity.

**Comment by Jack121Q** [comment]
Hey, I am the guy who did the facelift. This is the one bug that slipped by me, implemented this the day before release hoping to do something nice for you guys and give a reward when you finish the reconstruction. There is a fix posted on reddit and discord that I will copy-paste here for you.

Go to the mod's folder (If you are using steam, the mod id is 2438003901). 
Search for the file "TNO_Philippines_scripted_effects.txt . 
Open the file. 
And search for the following line of code 

JAP = { country_event = { id = PHI_Blitz.6 days = 1 } }

 . 
After you found the line of code, simply replace the "PHI_Blitz.6" portion with "jap_fopo.6".
The fixed version should look like this: 

JAP = { country_event = { id = jap_fopo.6" days = 1 } }

Now, with the fix done, all you have to do is load a save from BEFORE you completed the Philippines Reconstruction.

If for whatever reason you feel coding is out of your depth, I promise, this is really simple to do. But if you do not believe me, ping me here and I will post for you a copy of the file WITH the fix in it.

The fix is coming to the public build with the next hotfix. Sorry for inconvenience.

**Comment by runelead00** [comment]
Fixed in Dev Build

**Comment by MsChoo1** [comment]
> Hey, I am the guy who did the facelift. This is the one bug that slipped by me, implemented this the day before release hoping to do something nice for you guys and give a reward when you finish the reconstruction. There is a fix posted on reddit and discord that I will copy-paste here for you.
> 
> Go to the mod's folder (If you are using steam, the mod id is 2438003901). Search for the file "TNO_Philippines_scripted_effects.txt . Open the file. And search for the following line of code
> 
> JAP = { country_event = { id = PHI_Blitz.6 days = 1 } }
> 
> . After you found the line of code, simply replace the "PHI_Blitz.6" portion with "jap_fopo.6". The fixed version should look like this:
> 
> JAP = { country_event = { id = jap_fopo.6" days = 1 } }
> 
> Now, with the fix done, all you have to do is load a save from BEFORE you completed the Philippines Reconstruction.
> 
> If for whatever reason you feel coding is out of your depth, I promise, this is really simple to do. But if you do not believe me, ping me here and I will post for you a copy of the file WITH the fix in it.
> 
> The fix is coming to the public build with the next hotfix. Sorry for inconvenience.

Now when I press the button to complete reconstruction, it doesn't seem to do anything. Not sure if I entered anything wrong. Should look like this?
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/107003909/4efc532f-d504-49da-bcad-a99016e55295)

**Comment by MsChoo1** [comment]
> > Hey, I am the guy who did the facelift. This is the one bug that slipped by me, implemented this the day before release hoping to do something nice for you guys and give a reward when you finish the reconstruction. There is a fix posted on reddit and discord that I will copy-paste here for you.
> > Go to the mod's folder (If you are using steam, the mod id is 2438003901). Search for the file "TNO_Philippines_scripted_effects.txt . Open the file. And search for the following line of code
> > JAP = { country_event = { id = PHI_Blitz.6 days = 1 } }
> > . After you found the line of code, simply replace the "PHI_Blitz.6" portion with "jap_fopo.6". The fixed version should look like this:
> > JAP = { country_event = { id = jap_fopo.6" days = 1 } }
> > Now, with the fix done, all you have to do is load a save from BEFORE you completed the Philippines Reconstruction.
> > If for whatever reason you feel coding is out of your depth, I promise, this is really simple to do. But if you do not believe me, ping me here and I will post for you a copy of the file WITH the fix in it.
> > The fix is coming to the public build with the next hotfix. Sorry for inconvenience.
> 
> Now when I press the button to complete reconstruction, it doesn't seem to do anything. Not sure if I entered anything wrong. Should look like this? ![image](https://user-images.githubusercontent.com/107003909/271865447-4efc532f-d504-49da-bcad-a99016e55295.png)

Wait, nope! Worked fine. Thank you so much.
