### ISSUE TITLE
Country Affected - Short Description of Issue

### ISSUE THREAD

**Issue by shaqfor31** [TNODevs/TNO-Bug-Tracker#2662]
### Operating System

Windows 10

### HOI4 version

1.13

### TNO version

1.13

### Do you have other mods in use?

FPS Map/Goering Extended

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

TFV, DOD, WTT, LAR, AAT

### Files

[logs.zip](https://github.com/TNODevs/TNO-Bug-Tracker/files/13323357/logs.zip)

### Describe the crash

Essentially no matter whatever I do, my game will crash on October 4th, 1966 at 0200 Hours. I've tried launching other saves even as far back as a year to no effect. I'm wondering if my game is just broken or if theres a possible way of fixing the issue

### Steps to reproduce / Cause of the crash

1. Launch any save date
2. Play the game normally until October 4th, 1996
3. Game crashes
4. 

### Additional information

It would be nice knowing A) why the game is crashing if I ever want to restart a campaign or B) A fix to the game to prevent this for myself and others in the future

**Comment by runelead00** [comment]
We have no reports of this in base TNO and logs don't indicate any immediate problems caused by TNO other than a event firing in the wrong scope (which either submod related or the save broke at some point)
you should be able to extend your save a bit by annexing URG, but unclear how much longer if something fundamental is broken with the save or submod
