### ISSUE TITLE
About your official Twitter account

### ISSUE THREAD

**Issue by sat0510** [TNODevs/TNO-Bug-Tracker#2896]
### HOI4 version

This report is not game

### TNO version

This report is not game

### Describe your suggestion

Why your official Twitter's Japanese moderator uses it for private use? He or she sent reply to the Japanese musician and this is like to scream. Please do not use the account for private use.
I am sorry for I do not report it in right category but I could not find right category.

### Justifications

Official account should not be used for private use.

### Screenshots

![IMG_6885](https://github.com/TNODevs/TNO-Bug-Tracker/assets/91327260/1c6bab20-3794-42c3-a88a-3950064229af)

**Comment by runelead00** [comment]
I closed the original issue because this bug reporter is mean for issues relating to the mod itself, not the mod's  management, and the proper channels would have been to go directly to the TNO twitter or the feedback channel on the TNO discord server

However, after consulting with out twitter personnel, I have been directed to this thread for an explanation which should address your issue: https://twitter.com/polan9009/status/1737152625043517748
