### ISSUE TITLE
OVB - Incorrect Country Name

### ISSUE THREAD

**Issue by Marok132** [TNODevs/TNO-Bug-Tracker#3229]
### HOI4 version

1.14.2

### TNO version

1.5.0c

### Which major expansions do you NOT have?

I have all

### Describe your suggestion

Rename Ovamboland to Hereroland.

### Justifications

The name Ovamboland doesn't make any sense because it doesn't control states with Ovambo Population (they are controlled by Angola). I guess Hereroland is more accurate because the states it controls are populated by Herero. 

### Screenshots

![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/810c0c22-861d-4757-b984-34026fec403f)
![image](https://github.com/TNODevs/TNO-Bug-Tracker/assets/161346330/43e98920-7375-4481-9717-0261dc835d22)

**Comment by Stormeagle449** [comment]
First of all, Ovamboland isn't an ethnostate. The name comes from the Ovamboland People's Organization , which was founded by TNO's Ovamboland leader Ya Toivo. He was an anti apartheid activist and Namibian nationalist, and the tag's presence reflects that. It's not supposed to be an Ovambo ethnostate.

Secondly, as for patch 1.7.0, there's a state in Namibia with Ovambo culture and Ovamboland spawns there, so that should clear your issue.

**Comment by Marok132** [comment]
> First of all, Ovamboland isn't an ethnostate. The name comes from the Ovamboland People's Organization , which was founded by TNO's Ovamboland leader Ya Toivo. He was an anti apartheid activist and Namibian nationalist, and the tag's presence reflects that. It's not supposed to be an Ovambo ethnostate.
> 
> Secondly, as for patch 1.7.0, there's a state in Namibia with Ovambo culture and Ovamboland spawns there, so that should clear your issue.

Oh, alright. Thanks.
