### ISSUE TITLE
[Bug]: Almost All Countries Affected - Map is Almost Entirely White

### ISSUE THREAD

**Issue by Jaminator07** [TNODevs/TNO-Bug-Tracker#3294]
### Operating System

Windows 11

### HOI4 version

1.14.6

### TNO version

1.5.0d

### Do you have other mods in use?

Second West Russian War, Toolpack Without Errors

### Were you using Steam?

Yes

### Which major expansions do you NOT have?

I have all

### Describe the bug

All countries on the map except for Germany, Independent State of Serbia, Reichskommissariat Norwegen, Komi Republic, Imperial State of Iran, Regno d'Egetto, the African Reichskommissariats, and the Republic of China are white. 

### Steps to reproduce / Cause of the issue

1. Download Second West Russian War Submod and Toolpack without Errors mod, 2. Play with these mods for 3 or 4 sessions. The bug should occur on the 5th session. 3. Delete Toolpack without Errors and the bug is still there. 

### Expected behaviour

I expected the map to be colored properly with the nations.

**Comment by Lenzo2001** [comment]
Jaminator07, I experience the exact same problem on MacOS, even though I installed more TNO submods, like Göring expanded. Before you placed this issue, I did also place the issue here on Github and I also added a picture with it to show the devs what I meant.

**Comment by Lenzo2001** [comment]
Jaminator07, I hope you read this comment, but I found the source of the problem. If you want to get rid of those white colors, you have to delete the 2WRW. I know it's no fun, but it's the only way. I don't like it either because the mod Göring expanded always makes my game crash and the worst part about that mod is that this will update it when the new content for TNO comes out.

**Comment by runelead00** [comment]
As with every update, dont play submod until they are compatible
