### ISSUE TITLE
RUS - Regional Focus/Events won't load

### ISSUE THREAD

**Issue by DoomedDM** [TNODevs/TNO-Bug-Tracker#440]
**Questions**

- Operating System: Windows 10
- HOI4 Version: 1.10.8
- TNO Version: TT
- Any other mods in use: No
- Were you using Steam? Yes
- Which expansions do you NOT have? All of them 

**Longer Description of Issue:**
I have done two short playthroughs of two Russian warlords. Specifically:
- The Siberian Black Army 
and
- Soviet Komi (Bukharina)

In both of these playthroughs, the Regional Unifaction Button does change the tag and such of the country in question. Yet in both cases the new focus tree does not load, and in the case of the SBA the Communist Revolt from Central Siberian Warlords does not trigger. 

**Steps to Reproduce/Cause Issue:**

1. Reunify a section of Russia (by  using the Annex command to unify a region)

2. Click the reunification button

**Comment by runelead00** [comment]
Both of these focus tree transitions seem to work properly in the current game and needs info to confirm if actually a bug which are was Onega already dealt with in the Komi game and was the warlord expansion tree done, which I assume you likely no longer have or remember. 

As the revolt at regional, SBA is intended to not get it due to their specific politics
